# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Menu'),
        ),
    ]
