# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170601_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee', unique=True),
        ),
    ]
