# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170601_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('employee', 'menu')]),
        ),
    ]
