# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170601_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
